#!/bin/sh

usage() {
	echo "Usage: env KEY=<key> [LOG=<log>] $0 <trace files>"
}

gen_md5() {
	for orig in $*; do
		for suffix in anon anon-scanners; do
			f=$orig.$suffix
			m=`md5 -q $f`
			echo "Export: (for trace $f) [md5] $m" >> $LOG
		done
	done
}

gen_export() {
	grep '^Export: (for all' $LOG | sort > $LOG.export
	grep '^Export: (for trace' $LOG >> $LOG.export
	grep '^Export: (for packet' $LOG >> $LOG.export
}

if [ -z $KEY ]; then
	echo "Please define KEY"
	usage
	exit 1
fi

if [ -z $LOG ]; then
	LOG=tcpmkpub.log
fi

if [ -z `which md5` ]; then
	echo "Warning: md5 not found in PATH"
fi

if [ -e $LOG ]; then
	echo "$LOG already exists -- please remove it first"
	exit 1
else
	touch $LOG
fi

echo "logfile: $LOG"
chmod 600 $LOG

tcpmkpub -k $KEY -W $TCPMKPUB_FLAGS $* 2> $LOG

if grep -q 'Error' $LOG; then
	echo "There are errors in anonymization"
	echo "> grep Error $LOG | head"
	grep Error $LOG | head
	exit 1
fi

gen_md5 $* >> $LOG
gen_export
echo "tcpmkpub finishes successfully."
